DROP DATABASE IF EXISTS Market;
CREATE DATABASE Market;
USE Market;

CREATE TABLE Cart
(
  CID INT NOT NULL,
  PRIMARY KEY (CID)
);

CREATE TABLE Category
(
  CatName VARCHAR(50) NOT NULL,
  CatID INT NOT NULL,
  PRIMARY KEY (CatID)
);

CREATE TABLE Customer
(
  CustID INT NOT NULL,
  Name_ VARCHAR(50) NOT NULL,
  Email VARCHAR(500) NOT NULL,
  Password_ VARCHAR(50) NOT NULL,
  Gender VARCHAR(10),
  Phone_number VARCHAR(20),
  Balance FLOAT NOT NULL,
  DOB DATE,
  CID INT NOT NULL,
  UNIQUE(Email),
  PRIMARY KEY (CustID),
  FOREIGN KEY (CID) REFERENCES Cart(CID)
);

CREATE TABLE Product
(
  PID INT NOT NULL,
  Pname VARCHAR(50) NOT NULL,
  Price FLOAT NOT NULL,
  Stock_Quantity INT NOT NULL,
  ImageURL VARCHAR(500),
  CatID INT NOT NULL,
  PRIMARY KEY (PID),
  FOREIGN KEY (CatID) REFERENCES Category(CatID)
);

CREATE TABLE Orders
(
  OID INT NOT NULL,
  Date DATE,
  CustID INT NOT NULL,
  PRIMARY KEY (OID),
  FOREIGN KEY (CustID) REFERENCES Customer(CustID)
);

CREATE TABLE Contain
(
  Order_Quantity INT NOT NULL,
  PID INT NOT NULL,
  OID INT NOT NULL,
  PRIMARY KEY (PID, OID),
  FOREIGN KEY (PID) REFERENCES Product(PID),
  FOREIGN KEY (OID) REFERENCES Orders(OID)
);

CREATE TABLE Consists_of
(
  Product_Quantity INT NOT NULL,
  CID INT NOT NULL,
  PID INT NOT NULL,
  PRIMARY KEY (CID, PID),
  FOREIGN KEY (CID) REFERENCES Cart(CID),
  FOREIGN KEY (PID) REFERENCES Product(PID)
);